---
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-66
  reek:
    enabled: true
  flog:
    enabled: true
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-5
  editorconfig:
    enabled: true
