addons:
  postgresql: 9.6
  code_climate:
    repo_token: 597297b31ccbd95a18f77f2ff015da5e1a91d2eff63f4aff39e78d80d79e8aac
after_success:
- bundle exec codeclimate-test-reporter
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.5
