addons:
  postgresql: 9.6
before_script:
- bundle exec bin/rails db:setup
language: ruby
deploy:
  provider: heroku
  api_key:
    secure: "Jro99arEvqpAVdWBJRx3s38ga/qMA7uDYE8DMGO0i+J+Mohgnzo3uj20w0lfx+9BmNuti31ZGAuP0FAUnWgRKlL1luAG5sy63KlEM2o5DYB9MIktkdKK6liZlhGK7ecfl7wwo37x4FgA6MhfubsClrsA5TtQzRRhdJVPSQMp8nRn8x5AZOwXttJbcZTZ8sjqNcfbxJkUanxuqIESIsKjtVafE4CyFxkCaupngHUt+CD0gpMc4uJPUBHHOuOdOPEeOV2WlLWj4pH2E6vLc12pM67VrYhBgUSd07k/C3neUOf++J+aMjVWGHZZ94AJZCmeEb90t8IDy2qf1JJyzCKnU4Y78M9SMkucbMJglsw/e9nMHiZsztrab/24YhazdHjH2njYlIU6sevTttG+gufG3RWfsOiEH2UZjAuFjhwU5b1Zm1b/InjGgJfj27GNOES+tGO07lufwybmqA5TuqzF5IM5GUM4RQKpxXj6ouHYpTK12JUGmnCPzUGt6pzQPlVsZyHssN0efAu54Y4Grp31YS97Bb34bqa0SS0NbZL6+vwAk5fiN7zb9MjuRvdnDnEf8eJVEKdlpBarGVVwTcMQisXWWKjHlASZJQuTS4NiY1kxebT0hsgHc3uiYeCAGsnz66PJJ746SdOdFuWbzSCg9ZmUpptmUFY2E5zaXbctQY0="
  app: ulab-website-staging
  on:
    repo: ulab-committee/ulab-website
