version: 0.2

env:
  variables:
    RACK_ENV: test
    RAILS_ENV: test
    RAILS_SERVE_STATIC_FILES: enabled
    PGHOST: 127.0.0.1
    PGUSER: postgres
    PGPASSWORD: postgres

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 12
    commands:
      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli

      # Install Ruby dependencies from the Gemfile.
      - gem install bundler
      - bundle install
      # Install Yarn dependencies from package.json.
      - bundle exec yarn
      # Run Postgres
      - docker run postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      # Run Redis
      - docker run redis --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5 -p 6379:6379
      # Set up database
      - bundle exec rails db:setup

  pre_build:
    commands:
      # Set the SECRET_KEY_BASE environment variable for running tests
      - export SECRET_KEY_BASE=$(rake secret)

      # Run the tests using Rake.
      - bundle exec rake

  post_build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - template-export.yml
    - template-configuration.json
